### ISSUE TITLE
Restart Timer

### ISSUE THREAD

**Issue by xjacksssss** [noxsicarius/Custom-Debug-Monitor#5]
can i start by saying love the menu but im just wondering how i change the time before restart?

**Comment by noxsicarius** [comment]
That is not done with the tool. It requires a higher level of control than the game will allow a mod to have. You need something with administrative rights like using a binary file, process monitor system, or game hook like BEC.

**Comment by noxsicarius** [comment]
You mean the time shown on the debug? Change the math in this variable to whatever time you need 
_time = (round(180-(serverTime)/60));
